name: Release on Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        run: |
          mkdir -p bin
          javac -encoding UTF-8 -d bin src/**/*.java

      - name: Create JAR
        run: |
          jar cfe app.jar Main -C bin .

      - name: Package ZIP
        run: |
          zip -r app-bin.zip bin

      - name: Compute tag
        id: vars
        shell: bash
        run: echo "tag=v$(date +%Y%m%d-%H%M%S)-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: Release ${{ steps.vars.outputs.tag }}
          body: |
            Automated release from push to main.
            Commit: ${{ github.sha }}
          files: |
            app.jar
            app-bin.zip